spring:
  application:
    name: hello-spring-cloud-service-admin
  boot:
    admin:
      client:
        url: http://localhost:8084
  zipkin:
    base-url: http://localhost:9411
  spring: 
  rabbitmq:
    host: 
    port: 5672
    username: guest
    password: guest  
server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
